machines = {
    "master" => {"memory" => "512", "cpu" => "1", "ip" => "100", "image" => "bento/ubuntu-22.04"},
    "node01" => {"memory" => "512", "cpu" => "1", "ip" => "101", "image" => "bento/ubuntu-22.04"}
}

Vagrant.configure("2") do |config|

    config.vm.define "mysql" do
    config.vm.box = "hashicorp/bionic64"
    config.vm.provision "docker" do |d|
        d.run "ubuntu", cmd: "bash -l", args: "-v '/vagrant:/var/www'"
        d.run "mysqldb", image: "user/mysql"
    end

    machines.each do |name, conf|
        config.vm.define "#{name}" do |machine|
        machine.vm.box = "#{conf["image"]}"
        machine.vm.hostname = "#{name}"
        machine.vm.network "private_network", ip: "10.10.10.#{conf["ip"]}"
        machine.vm.provider "virtualbox" do |vb|
        vb.name = "#{name}"
        vb.memory = conf["memory"]
        vb.cpus = conf["cpu"]
    end
    machine.vm.provision "shell", path: "docker.sh"
    if "#{name}" == "master"
        machine.vm.provision "shell", path: "master.sh"
    else
        machine.vm.provision "shell", path: "worker.sh"
    end

end